# Generated by Django 4.0.1 on 2022-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contacts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
