# Generated by Django 4.0.1 on 2022-01-28 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contacts_file_alter_contacts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
