# Generated by Django 4.0.1 on 2022-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contacts_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
