# Generated by Django 4.0.1 on 2022-01-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
